/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.inrecolan.statistics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Statistics service. Represents a row in the &quot;Statistics_Statistics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.inrecolan.statistics.model.impl.StatisticsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.inrecolan.statistics.model.impl.StatisticsImpl}.
 * </p>
 *
 * @author sea
 * @see Statistics
 * @see ru.inrecolan.statistics.model.impl.StatisticsImpl
 * @see ru.inrecolan.statistics.model.impl.StatisticsModelImpl
 * @generated
 */
public interface StatisticsModel extends BaseModel<Statistics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a statistics model instance should use the {@link Statistics} interface instead.
	 */

	/**
	 * Returns the primary key of this statistics.
	 *
	 * @return the primary key of this statistics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this statistics.
	 *
	 * @param primaryKey the primary key of this statistics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stat ID of this statistics.
	 *
	 * @return the stat ID of this statistics
	 */
	public long getStatId();

	/**
	 * Sets the stat ID of this statistics.
	 *
	 * @param statId the stat ID of this statistics
	 */
	public void setStatId(long statId);

	/**
	 * Returns the user ID of this statistics.
	 *
	 * @return the user ID of this statistics
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this statistics.
	 *
	 * @param userId the user ID of this statistics
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this statistics.
	 *
	 * @return the user uuid of this statistics
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this statistics.
	 *
	 * @param userUuid the user uuid of this statistics
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this statistics.
	 *
	 * @return the group ID of this statistics
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this statistics.
	 *
	 * @param groupId the group ID of this statistics
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the action date of this statistics.
	 *
	 * @return the action date of this statistics
	 */
	public Date getActionDate();

	/**
	 * Sets the action date of this statistics.
	 *
	 * @param actionDate the action date of this statistics
	 */
	public void setActionDate(Date actionDate);

	/**
	 * Returns the action of this statistics.
	 *
	 * @return the action of this statistics
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this statistics.
	 *
	 * @param action the action of this statistics
	 */
	public void setAction(String action);

	/**
	 * Returns the portlet ID of this statistics.
	 *
	 * @return the portlet ID of this statistics
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this statistics.
	 *
	 * @param portletId the portlet ID of this statistics
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the url of this statistics.
	 *
	 * @return the url of this statistics
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this statistics.
	 *
	 * @param url the url of this statistics
	 */
	public void setUrl(String url);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Statistics statistics);

	public int hashCode();

	public CacheModel<Statistics> toCacheModel();

	public Statistics toEscapedModel();

	public Statistics toUnescapedModel();

	public String toString();

	public String toXmlString();
}